export type Rect = [xmin: number, xmax: number, ymin: number, ymax: number]
export type Matrix = [a: number, b: number, c: number, d: number, tx: number, ty: number]

/** One drawable layer (see tools/build_assets.py). */
export type Draw =
  | { b: number; x: number; y: number; w: number; h: number }
  | { b: number; m: Matrix; w: number; h: number }
  | { v: number; m: Matrix; x0: number; y0: number; w: number; h: number }

export interface Run<T> { from: number; to: number; rect?: Rect | null; draws?: number[]; clips?: string[]; value?: T }

/** A draw index, a sub-clip key ("iSata.mcConnector") drawn at its own frame,
 *  or a masked run: `items` are visible only inside the svg draw `mask` (Flash clip layers). */
export type FrameItem = number | string | { mask: number; items: FrameItem[] }

export interface ClipAssets {
  labels: Record<string, number>
  /** Per frame, back to front. */
  frames: FrameItem[][]
  /** Named children (hotspots, buttons, rotate tools) by frame range. */
  named: Record<string, { from: number; to: number; rect: Rect | null }[]>
}

/** Generated by tools/build_assets.py from a legacy lesson SWF. */
export interface LessonAssets {
  name: string
  width: number
  height: number
  fps: number
  rootLabels: Record<string, number>
  /** Root timeline: static draws and which clips are on stage, by frame range. */
  scenes: { from: number; to: number; draws: number[]; clips: string[] }[]
  clips: Record<string, ClipAssets>
  draws: Draw[]
}

export interface PartInfo {
  id: string
  name: { ar: string; fr: string; en: string }
  requires: string | null
  thumb: string
  image: string
  explore: string | null
}

// ---- Lesson programs (hand-written from the decompiled SWF scripts) ----

/** A frame number or a frame label of the clip. */
export type FrameRef = number | string

export type Step =
  /** Animate a clip frame by frame (either direction). */
  | { op: 'play'; clip: string; to: FrameRef; from?: FrameRef; wait?: boolean }
  /** Jump a clip to a frame. */
  | { op: 'goto'; clip: string; frame: FrameRef }
  /** Change the root scene (frame of the main timeline). */
  | { op: 'scene'; frame: FrameRef }
  | { op: 'show' | 'hide'; clips: string[] }
  /** Close-up: draw only these clips (null returns to the main scene). */
  | { op: 'view'; clips: string[] | null }
  /** Orientation puzzle: loop the clip between `range` with ↻/↺ until a correct frame, then play from `install`. */
  | { op: 'rotate'; clip: string; range: [FrameRef, FrameRef]; correct: [number, number][]; install: FrameRef; say: string }
  /** Wait until the student clicks the named child(ren) of a clip. */
  | { op: 'click'; clip: string; targets: string[]; all?: boolean; say: string }
  /** A big action button (e.g. "Install the motherboard"). */
  | { op: 'button'; label: string; say: string }
  | { op: 'done'; part: string }

export interface Task {
  id: string
  /** Tray part that starts this task when dropped on its hotspot.
   *  Tasks without a part start by themselves once their prerequisites are done. */
  part?: string
  /** Starts when the student clicks this child of a clip (e.g. a loose cable end). */
  start?: { clip: string; target: string }
  /** Clip holding the drop hotspot (defaults to the part id). */
  dropClip?: string
  /** Tasks that must be finished first. */
  after?: string[]
  /** Instruction while this task is the next thing to do. */
  say: string
  /** Short name in the lesson's step list (defaults to the part's name; hidden when neither exists). */
  label?: string
  steps: Step[]
}

export interface LessonProgram {
  file: string
  title: string
  /** Steps played once when the lesson opens (intro animation, initial visibility). */
  intro: Step[]
  /** Main scene frame the lesson returns to between tasks. */
  home: FrameRef
  tasks: Task[]
  /** Instruction when several tasks are possible. */
  idle?: string
  done: string
}
